ktor:
  application:
    modules:
      - org.course.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0
  database:
    host: localhost
    port: 5432
    name: course_db
    user: postgres
    password: postgres
  jwt:
    secret: secret_key_default
  upload:
    base_path: "uploads"